apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
  labels:
    app: devops
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops
        image: ismaeilshajar/devops-test-ismaeil
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_HOST
            value: mysql-db
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 30200
---
apiVersion: v1
kind: Service
metadata:
  name: devops
spec:
  type: NodePort
  selector:
    app: devops
  ports:
  - protocol: TCP 
    port: 30200
    targetPort: 30200

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  # ingressClassName: nginx
  rules:
    - http:
       paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: devops
              port: 
                number: 30200
